package day18_ExceptionHandeling;

import java.util.Scanner;

public class ExceptionsDemo {

	
	
	public static void main(String[] args) 
	{
		System.out.println("program is started....");
		
		Scanner sc=new Scanner(System.in);
		/*
		//Exp 1
		System.out.println("Enter a number");
		int num=sc.nextInt();
		
		System.out.println(100/num);   //Arithmetic exception
		
		
		System.out.println("Programm is completed ....");
		*/
		
		
		/*
		//Exp 2
		int a[]= new int [5];
		System.out.println("Enter the position 0-4:");
		int pos=sc.nextInt();
		
		System.out.println("enter a value");
		int value=sc.nextInt();
		
		a[pos]=value;   //ArrayIndexOutOfBoundsException
		
		System.out.println("Programm is completed ....");
		
		*/
		
		
		
		
	}
}
